model_name: Qwen/Qwen2.5-0.5B-Instruct
output_dir: runs/sft-qwen
train_file: data/processed/counselchat_train.jsonl
eval_file:  data/processed/counselchat_val.jsonl

per_device_train_batch_size: 2
gradient_accumulation_steps: 16
num_train_epochs: 1
learning_rate: 0.00001 
logging_steps: 20
save_steps: 200
bf16: true
report_to: tensorboard
